# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
fr:
  languageCode: fr-fr
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/fr/
  title: Mes publications en Français
  weight: 10

en:
  languageCode: en-US
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en/
  title: My posts in English
  weight: 20
# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
