 theme = "starter-hugo-academic"
title = "Boukary Ouedraogo"
baseurl = "https://www.boukary.fr/"
copyright = "© {year} Boukary Ouedraogo"
date = 2021-11-03T12:34:56+01:00
defaultContentLanguage = "fr"
#disableLanguages = "en"
hasCJKLanguage = false
defaultContentLanguageInSubdir = true
disableLanguageSwitchingButton = true
removePathAccents = true
enableGitInfo = true
summaryLength = 30
paginate = 10
enableEmoji = true
enableRobotsTXT = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = [
  "\\.ipynb$",
  ".ipynb_checkpoints$",
  "\\.Rmd$",
  "\\.Rmarkdown$",
  "_cache$",
 "\\.knit\\.md$", 
 "\\.utf8\\.md$"
]
disableAliases = true
math = true
pygmentsUseClasses = true
pygmentsCodefences = true
timeout = 600_000

[[module.imports]]
path = "github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms"

[[module.imports]]
path = "github.com/wowchemy/wowchemy-hugo-modules/wowchemy"

[languages.fr.permalinks]
event = "/talk/:slug/"
authors = "/author/:slug/"
tags = "/tag/:slug/"
categories = "/category/:slug/"
publication_types = "/publication-type/:slug/"
post = "/blog/:slug"

[languages.en.permalinks]
event = "/talk/:slug/"
authors = "/author/:slug/"
tags = "/tag/:slug/"
categories = "/category/:slug/"
publication_types = "/publication-type/:slug/"
post = "/blog/:slug"

[outputs]
home = [
  "HTML",
  "RSS",
  "JSON",
  "WebAppManifest",
  "headers",
  "redirects"
]
section = [ "HTML", "RSS" ]

[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe = true
  [markup.highlight]
  codeFences = true
  guessSyntax = true
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "pygments"
  tabWidth = 4

  [markup.tableOfContents]
  startLevel = 2
  endLevel = 3

[imaging]
resampleFilter = "lanczos"
quality = 75
anchor = "smart"

[taxonomies]
tag = "tags"
category = "categories"
publication_type = "publication_types"
author = "authors"

[related]
threshold = 80
includeNewer = true
toLower = true

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 70
[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
[security.funcs]
getenv = ['^HUGO_', '^WC_POST_CSS' ]